'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class GorselDBEntities1
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=GorselDBEntities1")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Asistans() As DbSet(Of Asistan)
    Public Overridable Property Derslers() As DbSet(Of Dersler)
    Public Overridable Property Dersliks() As DbSet(Of Derslik)
    Public Overridable Property Donems() As DbSet(Of Donem)
    Public Overridable Property Listes() As DbSet(Of Liste)
    Public Overridable Property Sinavs() As DbSet(Of Sinav)
    Public Overridable Property sysdiagrams() As DbSet(Of sysdiagram)
    Public Overridable Property Tarihlers() As DbSet(Of Tarihler)

End Class
