'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Yillar
    Public Property YilID As Integer
    Public Property Yil As Integer

    Public Overridable Property Sinav As ICollection(Of Sinav) = New HashSet(Of Sinav)

End Class
